# BenguelaShield - clamd runtime config
TCPSocket 3310
TCPAddr 127.0.0.1
MaxThreads 4
DatabaseDirectory C:\Users\carlo\antivirus\BenguelaShield\db
LogFile C:\Users\carlo\antivirus\BenguelaShield\logs\clamd.log
LogTime yes
PidFile C:\Users\carlo\antivirus\BenguelaShield\config\clamd.pid
Foreground yes
YaraRulesDir C:\Users\carlo\antivirus\BenguelaShield\modules\yara_engine\rules\benguelashield
